name: Build and Deploy Advent Calendar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: |
          mvn clean package

      # Archive the JAR file
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: advent-calendar-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      # Download the artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: advent-calendar-jar

      # Deploy the JAR to GitHub Pages
      - name: Deploy JAR to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          publish_branch: gh-pages
