name: Build and Deploy Advent Calendar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Verify Build Output
        run: ls -alh target

      - name: Create JAR file
        run: |
          mkdir -p downloads
          cp target/*.jar downloads/
          ls -alh downloads

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: advent-calendar-jar  # Ensure this matches the name in the deploy job
          path: downloads

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: advent-calendar-jar  # Match the name from the build job
          path: ./downloads

      - name: Commit and Push to Main
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add downloads/advent-calendar.jar
          git commit -m "Add built JAR file"
          git push origin main
