name: Build and Deploy Advent Calendar

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Verify Build Output
        run: ls -alh target

      - name: Create JAR file
        run: |
          mkdir -p docs/downloads
          cp target/*.jar docs/downloads/advent-calendar.jar
          ls -alh docs/downloads

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: advent-calendar-jar
          path: docs/downloads/advent-calendar.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: advent-calendar-jar
          path: ./docs/downloads

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./docs
          destination_dir: .
