name: Build JavaFX Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Adjust based on your JavaFX version
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Move JAR to downloads folder
        run: |
          mkdir -p downloads
          mv target/*.jar downloads/advent-calendar.jar

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: advent-calendar
          path: downloads/advent-calendar.jar